#define TITRE_FENETRE "Dig & Rush"
#define TAILLE_L 640
#define TAILLE_H 480
#define FPS 60

#define COULEUR_HITBOX_R 255
#define COULEUR_HITBOX_V 255
#define COULEUR_HITBOX_B 255
#define COULEUR_HITBOX_A 255

